---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/mentions
  label: Pages
  create: documents
  match: "**/*"
- type: directory
  path: content/runs
  label: Runs
  create: documents
  match: "**/*"
upload_dir: pictures
public_path: https://macojaune.com/.netlify/large-media/public/pictures
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
