import {projects,nodeById,accessible,done,status,resetData} from './data.js';
import {createWorld} from './world.js';
const $=id=>document.getElementById(id);let selected=null,panel=null,returnFocus=null,toastTimer;
const world=createWorld({canvas:$('scene'),container:$('world'),labels:$('labels'),onProject:showProject,onNode:showMission,onView:({zoom})=>{$('zoomIn').disabled=zoom>=3.39;$('zoomOut').disabled=zoom<=.66}});
function clearToast(){clearTimeout(toastTimer);$('announcement').classList.remove('visible')}
function choose(k){if(selected!==k)clearToast();selected=k;world.focusProject(k);updateDock();}
function updateDock(){if(!selected){$('dockTitle').textContent='Choisis ton terrain.';$('dockText').textContent='Touche un projet pour découvrir son histoire et ses missions.';$('dockCount').hidden=true;$('projectInfo').hidden=true;$('dockAction').innerHTML='Découvrir les projets <span aria-hidden="true">→</span>';return;}const p=projects[selected],n=nodeById(selected,p.selected);$('dockTitle').textContent=p.name;$('dockText').textContent=`${n.title} · ${status(selected,n)}`;$('dockCount').hidden=n.kind!=='count';$('dockCount').textContent=n.kind==='count'?`${n.count}/${n.goal}`:'';$('projectInfo').hidden=false;$('dockAction').innerHTML='Voir la Komisyon <span aria-hidden="true">→</span>';}
function openPanel(type,k,id){if($('sheetWrap').hidden)returnFocus=document.activeElement;panel={type,k,id};$('mapUI').inert=true;$('hardware').inert=true;$('sheetWrap').hidden=false;renderPanel();$('closeSheet').focus({preventScroll:true});$('sheetBody').scrollTop=0;}
function closePanel(){panel=null;$('sheetWrap').hidden=true;$('mapUI').inert=false;$('hardware').inert=false;const candidate=returnFocus?.isConnected&&!returnFocus.hidden?returnFocus:$('journal');candidate.focus({preventScroll:true});}
function showProject(k){choose(k);openPanel('project',k)}
function showMission(k,id){choose(k);const n=nodeById(k,id);if(n.kind==='intro'){showProject(k);return}projects[k].selected=id;world.visit(k,id);world.sync();updateDock();openPanel('mission',k,id);}
function projectHTML(k){const p=projects[k];return `<h2 id="sheetTitle">${p.name}</h2><p class="tagline">${p.tagline}</p><p>${p.description}</p><img class="preview" src="${p.image}" alt="Aperçu de l’interface ${p.name}"><p class="capture-note">Capture de l’interface · septembre 2026</p><div class="sheet-actions"><a class="action" href="${p.site}" target="_blank" rel="noopener">Explorer le site <span aria-hidden="true">↗</span></a>${p.video?`<a class="secondary" href="${p.video}" target="_blank" rel="noopener">Voir la vidéo</a>`:'<button class="secondary" disabled>Vidéo à venir</button>'}</div><p class="capture-note">La vidéo de présentation n’est pas encore ajoutée à cette démo.</p><h3>Les missions du projet</h3><div class="mission-list">${p.nodes.filter(n=>n.kind!=='intro').map(n=>`<button class="mission-link" data-mission="${n.id}"><span><strong>${n.title}</strong><small>${status(k,n)}${n.id==='partenaire'||n.id==='spots'?' · en parallèle':''}</small></span><span>${n.kind==='count'?`${n.count}/${n.goal}`:'→'}</span></button>`).join('')}</div><button class="action" data-explore style="margin-top:18px">Explorer ce territoire <span aria-hidden="true">→</span></button><p class="disclaimer">Objectifs et dépendances de démonstration, à définir ensemble.</p>`;}
function missionHTML(k,id){const p=projects[k],n=nodeById(k,id),isOpen=accessible(k,n),isDone=done(n),s=status(k,n),required=n.requires?nodeById(k,n.requires):null;let action='';if(n.kind==='count'&&!isDone)action=`<button class="action" id="simulate">${n.action}<span aria-hidden="true">+</span></button>`;else if(isDone){const follow=p.nodes.find(x=>x.requires===id);action=follow?`<button class="action" data-mission="${follow.id}">Explorer l’étape ouverte <span aria-hidden="true">→</span></button>`:'<button class="action" data-explore>Revenir au territoire <span aria-hidden="true">→</span></button>';}else if(!isOpen)action=`<button class="action" data-mission="${required.id}">Voir la mission nécessaire <span aria-hidden="true">→</span></button>`;else action='<button class="action" data-project-info>Revoir le projet <span aria-hidden="true">→</span></button>';
return `<h2 id="sheetTitle">${n.title}</h2><span class="status ${isDone?'done':isOpen?'active':''}">${s}</span><p>${n.intro}</p>${n.kind==='count'?`<div class="goal-counter"><strong>${n.count} / ${n.goal}</strong><span>${isDone?'Objectif atteint':`${n.goal-n.count} à réunir`}</span></div><div class="progress" role="progressbar" aria-label="${n.title}" aria-valuemin="0" aria-valuemax="${n.goal}" aria-valuenow="${n.count}">${Array.from({length:n.goal},(_,i)=>`<i class="${i<n.count?'filled':''}"></i>`).join('')}</div>`:''}<div class="effect"><strong>${isDone?'Ce qui a changé':!isOpen?'Pour ouvrir cette étape':'Ce que ça déclenche'}</strong><p>${!isOpen?`Atteindre ${required.goal} ${required.unit}${required.goal>1?'s':''}. Le contenu de cette étape reste consultable.`:isDone?(p.nodes.some(x=>x.requires===id)?'Le chemin suivant est ouvert. Tu peux maintenant en consulter la mission.':'Cette mission est remplie. Les autres chemins peuvent continuer à avancer.'):n.effect}</p></div>${action}<button class="secondary" data-project-info style="width:100%;margin-top:10px">Comprendre ${p.name}</button><p class="disclaimer">Simulation locale. Cliquer ici n’inscrit personne et ne publie aucun contenu.</p>`;}
function renderPanel(){const focused=document.activeElement?.id;$('sheetContext').hidden=panel.type==='project';$('sheetContext').textContent=panel.k?projects[panel.k].name:'LE CARNET';if(panel.type==='journal'){$('sheetBody').innerHTML=`<h2 id="sheetTitle">Choisis ton terrain.</h2><p>Deux projets, plusieurs façons de les faire avancer.</p>${Object.entries(projects).map(([k,p])=>`<article class="journal-entry"><h3>${p.name}</h3><p>${p.tagline}</p><button class="action" data-journal-project="${k}">Découvrir le projet <span aria-hidden="true">→</span></button></article>`).join('')}`;}else $('sheetBody').innerHTML=panel.type==='project'?projectHTML(panel.k):missionHTML(panel.k,panel.id);
$('sheetBody').querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>showMission(panel.k,b.dataset.mission));$('sheetBody').querySelectorAll('[data-project-info]').forEach(b=>b.onclick=()=>showProject(panel.k));$('sheetBody').querySelectorAll('[data-explore]').forEach(b=>b.onclick=closePanel);$('sheetBody').querySelectorAll('[data-journal-project]').forEach(b=>b.onclick=()=>showProject(b.dataset.journalProject));if($('simulate'))$('simulate').onclick=simulate;if(focused==='simulate')($('simulate')||$('sheetBody').querySelector('.action')).focus({preventScroll:true});}
function simulate(){if(panel?.type!=='mission')return;const {k,id}=panel,n=nodeById(k,id);if(n.kind!=='count'||done(n))return;n.count=Math.min(n.goal,n.count+1);if(done(n)){const follow=projects[k].nodes.find(x=>x.requires===id);if(follow)world.unlock(k,follow.id);$('announcement').querySelector('span').textContent='OBJECTIF ATTEINT';$('announcement').querySelector('strong').textContent=follow?'Un nouveau chemin est ouvert.':'Une Komisyon de plus, accomplie.';$('announcement').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('announcement').classList.remove('visible'),2200);$('live').textContent=`${projects[k].name}. ${n.title} : objectif atteint.`;}else $('live').textContent=`${n.title} : ${n.count} sur ${n.goal}.`;world.sync();updateDock();renderPanel();}
function overview(){if(panel)closePanel();selected=null;clearToast();world.overview();updateDock();}
$('closeSheet').onclick=closePanel;$('sheetWrap').onclick=e=>{if(e.target===$('sheetWrap'))closePanel()};$('sheet').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closePanel();return;}if(e.key==='Tab'){const items=Array.from($('sheet').querySelectorAll('button:not(:disabled),a[href],[tabindex="0"]'));if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
$('atlas').onclick=overview;$('recenter').onclick=overview;$('journal').onclick=()=>openPanel('journal');$('zoomIn').onclick=()=>world.scale(1.22);$('zoomOut').onclick=()=>world.scale(1/1.22);$('dockAction').onclick=()=>selected?showMission(selected,projects[selected].selected):openPanel('journal');$('projectInfo').onclick=()=>showProject(selected);$('hardwareAction').onclick=()=>$('dockAction').click();$('previous').onclick=()=>showProject('q');$('next').onclick=()=>showProject('s');$('reset').onclick=()=>{if(panel)closePanel();resetData();selected=null;clearToast();world.reset();updateDock();$('live').textContent='Démonstration réinitialisée.'};
window.__demo={getState:()=>({selected,panel:panel?{...panel}:null,projects:Object.fromEntries(Object.entries(projects).map(([k,p])=>[k,Object.fromEntries(p.nodes.filter(n=>n.kind==='count').map(n=>[n.id,n.count]))])),world:world.getState()}),projectPoint:world.projectPoint};updateDock();
