import * as THREE from '../node_modules/three/build/three.module.js';
const $=id=>document.getElementById(id);
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const projects={q:{name:'QuiLivreOù',goal:10,start:7,count:7,selected:1,names:['Projet découvert','10 inscrits','Vos retours','Premier partenaire'],short:['Découverte','Inscriptions','Retours','Partenaire']},s:{name:'Shootareas',goal:10,start:8,count:8,selected:1,names:['Le repérage','10 découvertes','La présentation','Vos spots'],short:['Repérage','Découvertes','Présentation','Spots']}};
let key='q',moving=null,unlockAt=0,toastTimer,frame=0,angle=.55,drag=null,lastRender=0;
const project=()=>projects[key],reached=()=>project().count>=project().goal,open=i=>i<=1||(i===2&&reached());
const positions=[new THREE.Vector3(-2.4,0,2.7),new THREE.Vector3(-.5,.3,.5),new THREE.Vector3(1.4,.6,-1.7),new THREE.Vector3(1.2,.9,-4.4)];
let renderer,scene,camera,world,pawn,bridges=[],rings=[],picks=[],labels=[],particles=[];
const palette={yellow:0xfbbf24,cream:0xffedbd,teal:0x098b83,side:0x06675f,ink:0x151c18};
const mat=color=>new THREE.MeshStandardMaterial({color,roughness:.78,metalness:0});
const mats={yellow:mat(palette.yellow),cream:mat(palette.cream),teal:mat(palette.teal),side:mat(palette.side),ink:mat(palette.ink),white:mat(0xf2f0d6),wood:mat(0x694e2d)};
function box(w,h,d,m,x=0,y=0,z=0,parent=world){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function cylinder(r1,r2,h,m,parent,segments=24){const v=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,segments),m);v.castShadow=true;v.receiveShadow=true;parent.add(v);return v;}
function drawFlag(parent,x,y,z){box(.065,1.15,.065,mats.ink,x,y+.57,z,parent);const flag=box(.62,.36,.045,mats.yellow,x+.3,y+.94,z,parent);flag.rotation.z=-.1;}
function setup(){try{renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();scene.background=new THREE.Color(0x161c1a);camera=new THREE.OrthographicCamera();world=new THREE.Group();scene.add(world);scene.add(new THREE.HemisphereLight(0xfff7df,0x5ba59d,2.6));const sun=new THREE.DirectionalLight(0xffffff,3.5);sun.position.set(-6,14,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:1,far:40});sun.shadow.bias=-.0004;sun.shadow.normalBias=.035;scene.add(sun);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(80,80),mat(0x080c09));floor.rotation.x=-Math.PI/2;floor.position.y=-1.62;floor.receiveShadow=true;scene.add(floor);
positions.forEach((p,i)=>{const group=new THREE.Group();group.position.copy(p);world.add(group);const base=box(2.55,1.35,2.2,[mats.teal,mats.side,mats.cream,mats.ink,mats.teal,mats.side],0,-.75,0,group);base.userData.node=i;picks.push(base);const cap=box(2.64,.13,2.28,mats.cream,0,-.015,0,group);cap.userData.node=i;picks.push(cap);const ring=cylinder(.46,.46,.055,i<2?mats.yellow:mats.ink,group,40);ring.position.y=.08;ring.userData.node=i;picks.push(ring);const inner=cylinder(.34,.34,.06,mats.ink,group,40);inner.position.y=.09;rings.push(ring);
if(i===0){const check=new THREE.Group();check.position.set(0,.14,0);const a=box(.1,.03,.27,mats.yellow,-.08,0,.03,check);a.rotation.y=-.8;const b=box(.1,.03,.46,mats.yellow,.08,0,-.03,check);b.rotation.y=.65;group.add(check);}
for(const [x,z,h]of [[-.98,-.73,.3],[.91,.72,.5]]){box(.29,h,.29,mats.teal,x,h/2+.05,z,group);box(.19,.2,.19,mats.yellow,x+.23,.15,z-.17,group)}
if(i===3){box(1.38,.18,1.05,mats.yellow,0,.18,-.12,group);for(const x of[-.55,.55])for(const z of[-.5,.28])box(.095,.75,.095,mats.yellow,x,.63,z,group);const roof=box(1.48,.18,1.18,mats.yellow,0,1.09,-.1,group);roof.rotation.z=.07;box(.5,.34,.4,mats.wood,0,.45,-.05,group);drawFlag(group,.5,1.18,-.25)}
const label=document.createElement('button');label.className='node-label';label.dataset.node=i;label.addEventListener('click',()=>select(i));$('labels').append(label);labels.push(label);
});
for(let i=0;i<3;i++){const g=new THREE.Group();world.add(g);const a=positions[i],b=positions[i+1];const steps=7;for(let j=0;j<steps;j++){const t=(j+1)/(steps+1);const v=new THREE.Vector3().lerpVectors(a,b,t);const part=box(.6,.14,.28,i===0?mats.yellow:mats.cream,v.x,v.y-.08,v.z,g);part.rotation.y=Math.atan2(b.x-a.x,b.z-a.z);}bridges.push(g)}
pawn=new THREE.Group();const body=cylinder(.13,.3,.55,mats.yellow,pawn);body.position.y=.34;const head=new THREE.Mesh(new THREE.SphereGeometry(.2,24,16),mats.yellow);head.position.y=.76;head.castShadow=true;pawn.add(head);const foot=cylinder(.32,.35,.07,mats.ink,pawn);foot.position.y=.05;world.add(pawn);pawn.position.copy(positions[1]);
resize();new ResizeObserver(resize).observe($('world'));$('scene').addEventListener('pointerdown',pointerDown);$('scene').addEventListener('pointermove',pointerMove);$('scene').addEventListener('pointerup',pointerUp);$('scene').addEventListener('pointercancel',()=>drag=null);$('scene').addEventListener('webglcontextlost',e=>{e.preventDefault();$('fallback').hidden=false;$('labels').style.display='none'});document.addEventListener('visibilitychange',()=>{if(!document.hidden)invalidate()});
}catch(e){$('fallback').hidden=false;console.error('3D indisponible',e);}}
function resize(){if(!renderer)return;const w=$('world').clientWidth,h=$('world').clientHeight;renderer.setSize(w,h,false);const span=w<450?11.9:10.1;camera.left=-span*w/h/2;camera.right=span*w/h/2;camera.top=span/2;camera.bottom=-span/2;camera.near=.1;camera.far=100;camera.updateProjectionMatrix();setCamera();invalidate();}
function setCamera(){camera.position.set(Math.sin(angle)*14,13,Math.cos(angle)*14);camera.lookAt(0,.2,-.65)}
function invalidate(){if(!frame)frame=requestAnimationFrame(render)}
function render(t){frame=0;if(!renderer||document.hidden)return;lastRender=t;let active=false;
if(moving){const raw=Math.min(1,(t-moving.start)/moving.duration);const v=1-Math.pow(1-raw,3);pawn.position.lerpVectors(moving.from,moving.to,v);pawn.position.y+=Math.sin(raw*Math.PI)*.58;active=raw<1;if(!active)moving=null;}
if(unlockAt){const u=reduce.matches?1:Math.min(1,(t-unlockAt)/1000);bridges[1].scale.y=Math.max(.01,u);bridges[1].position.y=(1-u)*-2.2;active=active||u<1;if(u>=1)unlockAt=0;}
for(let i=particles.length-1;i>=0;i--){const part=particles[i],age=(t-part.userData.start)/1000;part.position.copy(part.userData.origin).addScaledVector(part.userData.velocity,age);part.position.y-=age*age*2;part.rotation.x=age*5;part.rotation.z=age*3;if(age>1.6){world.remove(part);particles.splice(i,1)}else active=true;}
renderer.render(scene,camera);world.updateMatrixWorld(true);labels.forEach((el,i)=>{const v=positions[i].clone();v.z+=.8;v.y+=.07;v.applyMatrix4(world.matrixWorld).project(camera);const half=el.offsetWidth/2;const width=$('world').clientWidth;el.style.left=`${Math.max(half+6,Math.min(width-half-6,(v.x+1)*.5*width))}px`;el.style.top=`${(-v.y+1)*.5*$('world').clientHeight+(width<450&&i===0?20:0)}px`});if(active)invalidate();}
function pointerDown(e){drag={x:e.clientX,y:e.clientY,angle,moved:false};$('scene').setPointerCapture(e.pointerId)}
function pointerMove(e){if(!drag)return;const dx=e.clientX-drag.x;if(Math.abs(dx)>5){drag.moved=true;angle=Math.max(-.05,Math.min(1.15,drag.angle-dx*.004));setCamera();invalidate();}}
function pointerUp(e){if(!drag)return;const moved=drag.moved;drag=null;if(moved)return;const rect=$('scene').getBoundingClientRect();const mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);const ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(picks)[0];if(hit)select(hit.object.userData.node);}
function moveTo(i){if(!pawn)return;const from=pawn.position.clone(),to=positions[i].clone();if(reduce.matches){pawn.position.copy(to);moving=null}else moving={from,to,start:performance.now(),duration:650};invalidate();}
function select(i){const p=project();p.selected=Math.max(0,Math.min(3,i));if(open(p.selected))moveTo(p.selected);update();$('live').textContent=`${p.names[p.selected]}. ${open(p.selected)?'Étape accessible.':'Les conditions de cette étape ne sont pas encore remplies.'}`;}
function update(){const focusedStep=document.activeElement?.closest('#stepnav button')?.dataset.step;const p=project(),i=p.selected,done=reached();document.querySelectorAll('[data-project]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.project===key));$('stateLabel').textContent=i===0?'ACCOMPLI':i===1?(done?'KOMISYON REMPLIE':'EN COURS'):open(i)?'NOUVELLE ÉTAPE':'À VENIR';$('positionLabel').textContent=`ÉTAPE ${i+1} / 4`;$('missionTitle').textContent=p.names[i];$('count').hidden=i!==1;$('count').innerHTML=`${p.count}<span>/${p.goal}</span>`;$('progress').hidden=i!==1;$('progress').innerHTML=Array.from({length:p.goal},(_,n)=>`<i class="${n<p.count?'filled':''}"></i>`).join('');$('progress').setAttribute('aria-valuenow',p.count);let desc,action,disabled=false;
if(i===0){desc='Le projet est découvert. La première étape est derrière nous : place à la mission collective.';action='Rejoindre la mission';}
else if(i===1&&!done){desc=key==='q'?`Les premières personnes rejoignent QuiLivreOù. Encore ${p.goal-p.count} inscription${p.goal-p.count>1?'s':''} pour ouvrir la suite.`:`Des curieux découvrent Shootareas. Encore ${p.goal-p.count} découverte${p.goal-p.count>1?'s':''} avant la présentation.`;action=key==='q'?'Simuler une inscription':'Simuler une découverte';}
else if(i===1){desc='Objectif atteint ! Le passage est construit. La prochaine étape est maintenant accessible.';action='Découvrir la suite';}
else if(i===2&&done){desc=key==='q'?'Le passage est ouvert. La collecte de retours serait la prochaine mission ; son contenu reste à définir.':'La présentation serait maintenant débloquée. Dans cette démo, aucune vidéo ni publication réelle n’est déclenchée.';action='Revoir la mission accomplie';}
else{desc=i===2?`Cette étape s’ouvre lorsque la mission atteint ${p.goal} ${key==='q'?'inscrits':'découvertes'}.`:'Cette destination illustre la suite possible. Ses conditions restent à définir ensemble.';action='Revenir à la mission en cours';}
$('description').textContent=desc;$('action').innerHTML=`${action} <span aria-hidden="true">${i===1&&!done?'+':'→'}</span>`;$('action').disabled=disabled;
$('stepnav').innerHTML=p.short.map((s,n)=>`<button data-step="${n}" ${n===i?'aria-current="step"':''} aria-label="${p.names[n]}, ${open(n)?'accessible':'à venir'}">${s}</button>`).join('');$('stepnav').querySelectorAll('button').forEach(b=>b.onclick=()=>select(+b.dataset.step));if(focusedStep!==undefined)$('stepnav').querySelector(`[data-step="${focusedStep}"]`)?.focus({preventScroll:true});
labels.forEach((label,n)=>{label.setAttribute('aria-label',p.names[n]);label.innerHTML=`${n===1?p.names[n]:p.short[n]}<small>${n===0?'ACCOMPLI':n===1?`${p.count} / ${p.goal}`:open(n)?'OUVERT':'À VENIR'}</small>`;label.setAttribute('aria-pressed',n===i);label.dataset.locked=!open(n)});
if(renderer){bridges.forEach((b,n)=>{b.visible=n===0||(n===1&&done);});rings[1].material=mats.yellow;rings[2].material=done?mats.yellow:mats.ink;invalidate();}
}
function celebrate(){const t=performance.now();unlockAt=t;const origin=positions[1].clone();if(renderer&&!reduce.matches)for(let i=0;i<20;i++){const p=box(.07,.07,.15,i%3?mats.yellow:mats.cream);p.userData={start:t,origin:origin.clone().add(new THREE.Vector3(0,1,0)),velocity:new THREE.Vector3(Math.sin(i*2.4)*2,1.6+(i%5)*.25,Math.cos(i*2.4)*2)};particles.push(p)}$('announcement').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('announcement').classList.remove('visible'),2500);$('live').textContent='Komisyon remplie. Passage ouvert. La prochaine étape est disponible.';invalidate();}
function act(){const p=project();if(p.selected===1&&!reached()){p.count=Math.min(p.goal,p.count+1);if(reached())celebrate();else $('live').textContent=`${p.count} sur ${p.goal}.`;update();}else if(p.selected===1&&reached())select(2);else select(1);}
$('action').onclick=act;$('hardwareAction').onclick=act;$('previous').onclick=()=>select(project().selected-1);$('next').onclick=()=>select(project().selected+1);$('recenter').onclick=()=>{angle=.55;if(camera)setCamera();invalidate()};
document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{key=b.dataset.project;moving=null;unlockAt=0;clearTimeout(toastTimer);$('announcement').classList.remove('visible');for(const part of particles)world?.remove(part);particles=[];if(pawn)pawn.position.copy(positions[open(project().selected)?project().selected:1]);if(bridges[1]){bridges[1].scale.y=1;bridges[1].position.y=0}update()});
$('reset').onclick=()=>{for(const p of Object.values(projects)){p.count=p.start;p.selected=1}key='q';moving=null;unlockAt=0;for(const part of particles)world?.remove(part);particles=[];clearTimeout(toastTimer);$('announcement').classList.remove('visible');if(pawn)pawn.position.copy(positions[1]);if(bridges[1]){bridges[1].scale.y=1;bridges[1].position.y=0}update();$('live').textContent='Démonstration réinitialisée.'};
setup();update();
window.__demo={getState:()=>({project:key,count:project().count,selected:project().selected,nextOpen:reached(),bridgeVisible:bridges[1]?.visible,renderCalls:renderer?.info.render.calls}),projectNode:i=>{const v=positions[i].clone().applyMatrix4(world.matrixWorld).project(camera);return{x:(v.x+1)*.5*$('world').clientWidth,y:(-v.y+1)*.5*$('world').clientHeight}}};
