import {project,missions,createStore,statusFor,completedMainCount,deriveWorldState} from './model.js';
import {createWorld} from './world.js';
const $=id=>document.getElementById(id);
const icon=path=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"/></svg>`;
const arrow=icon('M4 12h15m-6-6 6 6-6 6');
const symbols={open:'M12 4v16M4 12h16',completed:'m5 12 4 4L19 6',blocked:'M6 10h12v11H6zM8 10V7a4 4 0 0 1 8 0v3'};
const stateNames={open:'Ouverte',completed:'Accomplie',blocked:'Bloquée'};
const store=createStore();let selected=null,panel=null,returnFocus=null,announceTimer,previous=store.getState(),world=null;
const getMission=id=>missions.find(m=>m.id===id);
function safeText(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function clearAnnouncement(){clearTimeout(announceTimer);$('announcement').classList.remove('visible');}
function announce(title,message){$('announceTitle').textContent=title;$('announceText').textContent=message;$('announcement').classList.add('visible');$('live').textContent=`${title}. ${message}`;clearTimeout(announceTimer);announceTimer=setTimeout(clearAnnouncement,4200);}
function updateDock(state){const count=completedMainCount(state);$('repairCount').innerHTML=`${count}<span>/3</span>`;$('depotTitle').textContent=state.repaired?'LE DÉPÔT REPART !':count?'ÇA REPREND VIE.':'ON EST À L’ARRÊT.';$('depotText').textContent=state.repaired?'Le Fenwick Q est réparé. Les colis peuvent bouger.':count===1?'L’alimentation est revenue. On continue ?':count===2?'Encore une mission avant le redémarrage.':'Le Fenwick Q attend un coup de main.';[...$('repairTrack').children].forEach((el,i)=>el.classList.toggle('filled',i<count));}
function closePanel(){panel=null;$('sheetWrap').hidden=true;$('mapUI').inert=false;$('hardware').inert=false;const target=returnFocus?.isConnected&&!returnFocus.hidden?returnFocus:$('missionsButton');target.focus({preventScroll:true});}
function openPanel(type,id){clearAnnouncement();if(!panel)returnFocus=document.activeElement;panel={type,id};if(type==='mission')selected=id;else if(type==='project')selected='project';world?.setState(deriveWorldState(store.getState(),selected),{animate:false});$('mapUI').inert=true;$('hardware').inert=true;$('sheetWrap').hidden=false;renderPanel();$('sheetBody').scrollTop=0;$('sheetClose').focus({preventScroll:true});}
function chip(id,state){const status=statusFor(id,state);return `<span class="state-chip ${status}">${icon(symbols[status])}${stateNames[status]}</span>`;}
function listHTML(state){return `<div class="mission-list">${missions.map((m,i)=>{const status=statusFor(m.id,state);return `<button class="mission-item" data-mission="${m.id}" data-state="${status}"><span class="mission-code">${m.role==='bonus'?'+':String(i+1).padStart(2,'0')}</span><span class="mission-content"><strong>${safeText(m.title)}</strong><small>${stateNames[status]} · ${m.role==='bonus'?'Bonus indépendant':'Mission principale'}</small></span><span class="mission-count">${state.counts[m.id]}/${m.goal}</span></button>`;}).join('')}</div>`;}
function projectHTML(state){return `<h2 id="sheetTitle">${project.name}</h2><p class="tagline">${project.tagline}</p><p>${project.description}</p><img class="preview" src="${project.image}" alt="Aperçu du site QuiLivreOù, annuaire de boutiques"><p class="caption">Capture du site · septembre 2026</p><div class="sheet-actions"><a class="action" href="${project.site}" target="_blank" rel="noopener">Explorer le site ${arrow}</a>${project.video?`<a class="secondary" href="${project.video}" target="_blank" rel="noopener">Voir la vidéo</a>`:'<button class="secondary" disabled>Vidéo à venir</button>'}</div><h3>POURQUOI CE DÉPÔT ?</h3><p>Les colis sont là. Mais pour arriver jusqu’à chez nous, le chemin se complique. Le Fenwick Q raconte ce blocage : les missions le remettent en marche.</p><p>Cette réparation est une métaphore du jeu. QuiLivreOù aide à trouver des boutiques ; ce n’est pas un service de transport.</p><button class="action" data-view="missions">${state.repaired?'Revoir les missions':'Réveiller le dépôt'} ${arrow}</button><p class="note">Prototype : les objectifs sont fictifs. La vidéo de présentation n’est pas encore ajoutée.</p>`;}
function missionsHTML(state){return `<h2 id="sheetTitle">ON DÉBLOQUE ÇA ?</h2><p>Trois missions principales pour réparer le Fenwick Q. Chaque réussite change quelque chose dans le dépôt.</p>${listHTML(state)}<p class="note">Objectifs de démonstration. Leurs critères réels seront choisis au cas par cas. Les bonus enrichissent le lieu sans remplacer les réparations.</p><button class="secondary" data-explore style="width:100%;margin-top:16px">Retour au dépôt</button>`;}
function missionHTML(id,state){const m=getMission(id),status=statusFor(id,state),done=status==='completed',blocked=status==='blocked',requires=m.requires?getMission(m.requires):null,count=state.counts[id],next=missions.find(x=>x.requires===id);return `<h2 id="sheetTitle">${safeText(m.title)}</h2>${chip(id,state)}<p>${safeText(m.description)}</p><div class="goal"><strong>${count}<span style="font:inherit;color:#637353"> / ${m.goal}</span></strong><span>${done?'OBJECTIF ATTEINT':`${Math.max(0,m.goal-count)} à réunir`}</span></div><div class="goal-bar" role="progressbar" aria-label="${safeText(m.title)}" aria-valuemin="0" aria-valuemax="${m.goal}" aria-valuenow="${Math.min(count,m.goal)}" aria-valuetext="${count} sur ${m.goal}"><i style="transform:scaleX(${Math.min(1,count/m.goal)})"></i></div><div class="effect"><strong>${blocked?'D’ABORD, CETTE ÉTAPE':done?'ÇA A CHANGÉ LE DÉPÔT':'CE QUE ÇA VA CHANGER'}</strong><p>${blocked?`Accomplir « ${safeText(requires.title)} » ouvre cette mission.`:safeText(m.effect)}</p></div>${blocked?`<button class="action" data-mission="${requires.id}">Voir la mission nécessaire ${arrow}</button>`:done?`<button class="action" data-explore>Voir le dépôt ${arrow}</button>${next?`<button class="secondary" data-mission="${next.id}" style="width:100%;margin-top:9px">La mission suivante ${arrow}</button>`:''}`:`<button id="contribute" class="action">${safeText(m.action)} ${arrow}</button>`}<p class="note">Simulation : ce bouton ne crée aucune inscription, n’envoie aucun message et ne modifie pas le vrai site.</p>`;}
function demoHTML(){const items=[['start','Le dépôt à l’arrêt','7 inscrits, aucune réparation.','M12 4v8m-6-7a8 8 0 1 0 12 0'],['progress','Ça reprend vie','Alimentation réparée, retours en cours.','m5 12 4 4L19 6'],['repaired','Le grand redémarrage','Les trois principales sont accomplies.','M5 4h14v12H5zM8 16v4m8-4v4M2 20h20'],['bonus','Le bonus, tout seul','Le décor change. Le Fenwick reste en panne.','m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9z']];return `<h2 id="sheetTitle">ESSAIE LES ÉTATS.</h2><p>Choisis un point de départ, puis explore les missions et leurs effets sur le dépôt.</p>${items.map(([id,title,desc,shape])=>`<button class="preset" data-preset="${id}"><span>${icon(shape)}</span><span><strong>${title}</strong><small>${desc}</small></span></button>`).join('')}<p class="note">Ces commandes remplacent l’avancement de cette démo dans ce navigateur. Elles ne touchent aucune donnée réelle.</p><button class="secondary" id="resetDemo" style="width:100%;margin-top:15px">Tout réinitialiser</button>`;}
function renderPanel(){if(!panel)return;const state=store.getState(),wasContribute=document.activeElement?.id==='contribute';$('sheetBack').hidden=panel.type!=='mission';$('sheetBody').innerHTML=panel.type==='project'?projectHTML(state):panel.type==='mission'?missionHTML(panel.id,state):panel.type==='demo'?demoHTML():missionsHTML(state);$('sheetBody').querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>openPanel('mission',b.dataset.mission));$('sheetBody').querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openPanel(b.dataset.view));$('sheetBody').querySelectorAll('[data-explore]').forEach(b=>b.onclick=closePanel);$('sheetBody').querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{closePanel();selected=null;store.preset(b.dataset.preset);});if($('resetDemo'))$('resetDemo').onclick=()=>{closePanel();selected=null;store.reset();world?.resetView();};if($('contribute'))$('contribute').onclick=()=>{const id=panel.id;const result=store.contribute(id,crypto.randomUUID());if(result.ok&&store.getState().completed.includes(id)){closePanel();}};if(wasContribute)$('contribute')?.focus({preventScroll:true});}
store.subscribe(state=>{const completed=state.completed.filter(id=>!previous.completed.includes(id));const justRepaired=state.repaired&&!previous.repaired;updateDock(state);world?.setState(deriveWorldState(state,selected),{animate:completed.length>0});renderPanel();if(justRepaired)announce('LES TROIS MISSIONS SONT ACCOMPLIES','LE DÉPÔT REPREND VIE.');else if(completed.length===1){const m=getMission(completed[0]);announce(m.role==='bonus'?'BONUS ACCOMPLI':'MISSION ACCOMPLIE',m.role==='bonus'?'UNE NOUVELLE TOUCHE AU DÉPÔT.':`${completedMainCount(state)}/3 · ON AVANCE !`);}else clearAnnouncement();previous=state;});
$('missionsButton').onclick=() =>openPanel('missions');$('hardwareAction').onclick=$('missionsButton').onclick;$('projectButton').onclick=()=>openPanel('project');$('infoButton').onclick=$('projectButton').onclick;$('demoButton').onclick=()=>openPanel('demo');$('sheetBack').onclick=()=>openPanel('missions');$('sheetClose').onclick=closePanel;$('sheetWrap').onclick=e=>{if(e.target===$('sheetWrap'))closePanel();};$('dismissAnnouncement').onclick=clearAnnouncement;$('zoomIn').onclick=()=>world?.zoomBy(1.2);$('zoomOut').onclick=()=>world?.zoomBy(1/1.2);$('recenter').onclick=()=>world?.resetView();$('hardwareView').onclick=$('recenter').onclick;
$('sheet').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closePanel();}else if(e.key==='Tab'){const f=[...$('sheet').querySelectorAll('button:not(:disabled):not([hidden]),a[href]')].filter(el=>el.getClientRects().length);const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus({preventScroll:true});}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus({preventScroll:true});}}});
$('scene').addEventListener('webglcontextlost',()=>{$('fallback').hidden=false;});
$('scene').addEventListener('webglcontextrestored',()=>{$('fallback').hidden=true;});
updateDock(previous);
try{world=createWorld({canvas:$('scene'),container:$('world'),labels:$('labels'),onSelect:id=>openPanel(id==='project'?'project':'mission',id)});world.setState(deriveWorldState(previous,selected),{animate:false});$('loading').hidden=true;}catch(error){$('loading').hidden=true;$('fallback').hidden=false;console.error(error);}
window.__demo={getState:()=>store.getState(),getWorld:()=>world?.getDebug(),projectPoint:id=>world?.projectPoint(id),getPanel:()=>panel?{...panel}:null};
window.addEventListener('pagehide',()=>world?.dispose(),{once:true});
