const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});const reports=[];fs.mkdirSync('.impeccable/review',{recursive:true});
 for(const [name,size] of Object.entries({desktop:{width:1280,height:900},mobile:{width:390,height:844},small:{width:360,height:740}})){
  const ctx=await browser.newContext({viewport:size,hasTouch:name!=='desktop'});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
  await p.goto(process.env.DEMO_URL||'http://127.0.0.1:58014/');await p.waitForFunction(()=>window.__demo?.getWorld()?.renderCalls>0);await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(700);
  const bounds=await p.locator('.console').boundingBox(),screen=await p.locator('.screen').boundingBox();
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight),true,'page overflow');
  await p.screenshot({path:`.impeccable/review/${name}.png`,fullPage:true});
  assert.equal(await p.locator('#fallback').isVisible(),false);
  await p.locator('#projectButton').click();assert.equal(await p.locator('#sheetTitle').textContent(),'QuiLivreOù');assert.equal(await p.locator('#sheet a.action').getAttribute('href'),'https://quilivreou.marvinl.com');assert.equal(await p.getByRole('button',{name:'Vidéo à venir'}).isDisabled(),true);
  if(name!=='small')await p.screenshot({path:`.impeccable/review/${name}-project.png`,fullPage:true});
  await p.locator('#sheetClose').focus();await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.hasAttribute('data-view')),true,'reverse focus trap');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.id),'sheetClose');await p.keyboard.press('Escape');
  await p.locator('#missionsButton').click();await p.locator('[data-mission=retours]').click();assert.match(await p.locator('.state-chip').textContent(),/Bloquée/);assert.equal(await p.locator('#contribute').count(),0);await p.locator('[data-mission=inscrits]').click();
  await p.locator('#contribute').focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>__demo.getState().counts.inscrits),8);assert.equal(await p.evaluate(()=>document.activeElement.id),'contribute');await p.keyboard.press('Enter');await p.keyboard.press('Enter');await p.waitForTimeout(500);
  assert.equal(await p.locator('#sheetWrap').isVisible(),false);assert.equal(await p.evaluate(()=>__demo.getState().completed.includes('inscrits')),true);
  await p.locator('#missionsButton').click();await p.locator('[data-mission=retours]').click();for(let i=0;i<3;i++)await p.locator('#contribute').click();await p.locator('#missionsButton').click();await p.locator('[data-mission=boutiques]').click();for(let i=0;i<5;i++)await p.locator('#contribute').click();
  assert.equal(await p.evaluate(()=>__demo.getState().repaired),true);await p.waitForTimeout(4600);assert.deepEqual(await p.locator('.console').boundingBox(),bounds,'device moved');assert.deepEqual(await p.locator('.screen').boundingBox(),screen,'screen changed');await p.screenshot({path:`.impeccable/review/${name}-repaired.png`,fullPage:true});
  await p.reload();await p.waitForFunction(()=>window.__demo?.getWorld()?.renderCalls>0);assert.equal(await p.evaluate(()=>__demo.getState().repaired),true);assert.equal(await p.locator('#announcement').evaluate(el=>el.classList.contains('visible')),false,'reload replays announcement');
  await p.locator('#demoButton').click();await p.locator('[data-preset=bonus]').click();assert.equal(await p.evaluate(()=>__demo.getState().repaired),false);assert.deepEqual(await p.evaluate(()=>__demo.getState().completed),['bonus']);await p.waitForTimeout(1000);if(name==='mobile')await p.screenshot({path:'.impeccable/review/mobile-bonus.png',fullPage:true});
  await p.locator('#demoButton').click();await p.locator('[data-preset=progress]').click();assert.equal(await p.evaluate(()=>__demo.getState().counts.retours),1);
  const z=await p.evaluate(()=>__demo.getWorld().zoom);await p.locator('#zoomIn').click();assert.ok(await p.evaluate(()=>__demo.getWorld().zoom)>z);await p.locator('#zoomOut').click();
  const canvas=await p.locator('#scene').boundingBox(),before=await p.evaluate(()=>__demo.getWorld().target);await p.mouse.move(canvas.x+canvas.width*.15,canvas.y+canvas.height*.9);await p.mouse.down();await p.mouse.move(canvas.x+canvas.width*.15+50,canvas.y+canvas.height*.9+15,{steps:5});await p.mouse.up();assert.notDeepEqual(await p.evaluate(()=>__demo.getWorld().target),before);await p.locator('#recenter').click();
  await p.emulateMedia({reducedMotion:'reduce'});await p.locator('#demoButton').click();await p.locator('#resetDemo').click();assert.equal(await p.evaluate(()=>__demo.getState().counts.inscrits),7);assert.deepEqual(await p.locator('.console').boundingBox(),bounds);
  assert.deepEqual(errors,[]);reports.push({viewport:size,deviceStable:true,projectAndKeyboard:true,allRepairs:true,bonusIndependent:true,persistence:true,panZoom:true,errors});await ctx.close();
 }
 const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await ctx.newPage();await p.goto(process.env.DEMO_URL||'http://127.0.0.1:58014/');await p.waitForFunction(()=>window.__demo?.getWorld()?.renderCalls>0);const c=await p.locator('#scene').boundingBox(),x=c.x+c.width/2,y=c.y+c.height*.82,z=await p.evaluate(()=>__demo.getWorld().zoom),cdp=await ctx.newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y,id:1},{x:x+25,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-55,y,id:1},{x:x+55,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await p.evaluate(()=>__demo.getWorld().zoom)>z);await ctx.close();
 fs.writeFileSync('.impeccable/review/verification.json',JSON.stringify({reports,pinchZoom:true,realPhone:false},null,2));await browser.close();console.log('V3 browser verification passed:',reports.length,'viewports + pinch.');
})().catch(e=>{console.error(e);process.exit(1)});
